apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  Setup:
    steps:
      - name: Setup Git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

  Checkout: 
    needs: Setup
    steps:   
    - name: Checkout
      uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout 
    steps:
      - name: set .mvn path
        uses: docker://maven:latest
        entrypoint: ["/bin/sh", "-c"]
        run: echo "::add-path::$MAVEN_HOME/.mvn/wrapper"

      - name: Build with Maven
        uses: docker://maven:latest
        shell: sh
        entrypoint: ["/bin/sh", "-c"]
        run: |
          pwd
          ls -la
          mvn clean package
