apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global -add safe.directory /cloudbees/workspace
          
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build petstore clinic
        uses: docker://maven:latest
        shell: sh
        run: |
          pwd
          ls -la
          echo $JAVA_HOME
          ./mvnw clean install
